### ISSUE TITLE
Docker compose images do not work. 

### ISSUE THREAD

**Issue by develroo** [varchashva/LetsMapYourNetwork#14]
Seems to be a configuration isssue. For one thing going to the default port host:9999 brings you to the default Django landing page. 

![Screenshot from 2019-05-08 11-50-18](https://user-images.githubusercontent.com/7777993/57370255-996b9900-7187-11e9-8b9d-ddfa3b6e71b4.png)

When navigating to core default statisics page shows ok.:

![Screenshot from 2019-05-08 13-34-47](https://user-images.githubusercontent.com/7777993/57375756-287fad80-7196-11e9-8f06-a7592cf9fbc8.png)

But trying to create a project fails. 

![Screenshot from 2019-05-08 13-36-17](https://user-images.githubusercontent.com/7777993/57375825-549b2e80-7196-11e9-9f7d-e24ccadb8bc6.png)

![Screenshot from 2019-05-08 13-37-04](https://user-images.githubusercontent.com/7777993/57375847-67adfe80-7196-11e9-83e8-69a015a3b662.png)

Even replacing //action with /action fails to find files. 

This was creating the containers from the docker-compose.yml file. 

For reference docker engine version is 18.09.6 and docker-compose version  is 1.24.0-rc3, build 42894249 both on Debian Stretch.

**Comment by varchashva** [comment]
Hi @develroo 
can you please select 'default' project from 'Select Project' drop-down in top right corner and then try to create new project.

**Comment by varchashva** [comment]
> Seems to be a configuration isssue. For one thing going to the default port host:9999 brings you to the default Django landing page.
> 
> ![Screenshot from 2019-05-08 11-50-18](https://user-images.githubusercontent.com/7777993/57370255-996b9900-7187-11e9-8b9d-ddfa3b6e71b4.png)
> 
> When navigating to core default statisics page shows ok.:
> 
> ![Screenshot from 2019-05-08 13-34-47](https://user-images.githubusercontent.com/7777993/57375756-287fad80-7196-11e9-8f06-a7592cf9fbc8.png)
> 
> But trying to create a project fails.
> 
> ![Screenshot from 2019-05-08 13-36-17](https://user-images.githubusercontent.com/7777993/57375825-549b2e80-7196-11e9-9f7d-e24ccadb8bc6.png)
> 
> ![Screenshot from 2019-05-08 13-37-04](https://user-images.githubusercontent.com/7777993/57375847-67adfe80-7196-11e9-83e8-69a015a3b662.png)
> 
> Even replacing //action with /action fails to find files.
> 
> This was creating the containers from the docker-compose.yml file.
> 
> For reference docker engine version is 18.09.6 and docker-compose version is 1.24.0-rc3, build 42894249 both on Debian Stretch.

hey @develroo, are you able to access the application as mentioned above? thanks

**Comment by develroo** [comment]
Yes.. That seems to allow the creation of other Project names. Though it is hardly what I would call intuative. Some smarter URL handling and some landing pages might be a better solution. 

Will test it in other areas now see if it works ok.
