### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by lupus721** [varchashva/LetsMapYourNetwork#19]
I run it in my server use docker-compose ,and visit it by chrome form my pc ,when the page notice some error 

`
Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:7474/db/data/transaction/commit
`
maybe it's something error

**Comment by varchashva** [comment]
hi @lupus721 

as mentioned in installation guidelines, docker-compose works for Linux only, because of docker-compose limitation - docker/compose#4799 (comment)
