### ISSUE TITLE
Default credentials

### ISSUE THREAD

**Issue by baiolo** [varchashva/LetsMapYourNetwork#23]
There is no information about the login credentials, or al least I didn't find them anywhere.
I'm LMYN via Docker compose.

**Comment by varchashva** [comment]
hi @baiolo - there is no credentials for "front-end" of product. You just have to run the container (local machine) and browse to URL. Please share screenshot if you are facing other problems.

Thanks!

**Comment by baiolo** [comment]
My fault, didn't realize that the `/admin` path is not used by the project :pray:
