### ISSUE TITLE
Using Docker Compose not working

### ISSUE THREAD

**Issue by brownsec** [varchashva/LetsMapYourNetwork#9]
I am using Docker compose to test it out, but i cant get it to work

Seems like "Neo4j is up" according to the output but curl -v http://localhost:7474/ gives connection refused. 

sudo docker-compose up
Password:
Starting letsmapyournetwork_neo4j_1 ... done
Starting letsmapyournetwork_lmyn_1  ... done
Attaching to letsmapyournetwork_neo4j_1, letsmapyournetwork_lmyn_1
lmyn_1   | Neo4j isn't available. Let's wait for sometime
lmyn_1   | python manage.py runserver 0.0.0.0:9999
neo4j_1  | Active database: graph.db
neo4j_1  | Directories in use:
neo4j_1  |   home:         /var/lib/neo4j
neo4j_1  |   config:       /var/lib/neo4j/conf
neo4j_1  |   logs:         /var/lib/neo4j/logs
neo4j_1  |   plugins:      /var/lib/neo4j/plugins
neo4j_1  |   import:       /var/lib/neo4j/import
neo4j_1  |   data:         /var/lib/neo4j/data
neo4j_1  |   certificates: /var/lib/neo4j/certificates
neo4j_1  |   run:          /var/lib/neo4j/run
neo4j_1  | Starting Neo4j.
neo4j_1  | 2018-12-19 22:30:49.570+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
neo4j_1  | 2018-12-19 22:30:49.578+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
neo4j_1  | 2018-12-19 22:30:49.578+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
neo4j_1  | 2018-12-19 22:30:49.578+0000 WARN  Unknown config option: ha.host.coordination
neo4j_1  | 2018-12-19 22:30:49.579+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
neo4j_1  | 2018-12-19 22:30:49.579+0000 WARN  Unknown config option: causal_clustering.discovery_advertised_address
neo4j_1  | 2018-12-19 22:30:49.579+0000 WARN  Unknown config option: ha.host.data
neo4j_1  | 2018-12-19 22:30:49.579+0000 WARN  Unknown config option: causal_clustering.transaction_listen_address
lmyn_1   | Neo4j isn't available. Let's wait for sometime
lmyn_1   | python manage.py runserver 0.0.0.0:9999
neo4j_1  | 2018-12-19 22:30:49.619+0000 INFO  ======== Neo4j 3.3.0 ========
neo4j_1  | 2018-12-19 22:30:49.685+0000 INFO  Starting...
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | Neo4j isn't available. Let's wait for sometime
neo4j_1  | 2018-12-19 22:30:51.135+0000 INFO  Bolt enabled on 0.0.0.0:7687.
lmyn_1   | Neo4j isn't available. Let's wait for sometime
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | Neo4j isn't available. Let's wait for sometime
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | Neo4j isn't available. Let's wait for sometime
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | Neo4j isn't available. Let's wait for sometime
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | Neo4j isn't available. Let's wait for sometime
neo4j_1  | 2018-12-19 22:30:55.935+0000 INFO  Started.
lmyn_1   | python manage.py runserver 0.0.0.0:9999
lmyn_1   | Neo4j isn't available. Let's wait for sometime
neo4j_1  | 2018-12-19 22:30:57.316+0000 INFO  Remote interface available at http://localhost:7474/
lmyn_1   | HTTP/1.1 200 OK
lmyn_1   | Neo4j is up now. Let's go...

**Comment by varchashva** [comment]
Hey @brownsec 
can you let me know:
1. which OS you are using? (kindly note that docker installation will work with **_Linux distros_** only, as of now)
2. what error you are getting while browsing http://localhost:9999/core? 

Thanks!

**Comment by brownsec** [comment]
@varchashva 

I was using macOS (10.12.6 ) originally, but than i switched to Kali and its all working.

Thanks,

**Comment by varchashva** [comment]
Thanks @brownsec for confirmation, make it working in Mac is in my radar.

Do let me know your feedback.
